### ISSUE TITLE
docker alpine cowboy

### ISSUE THREAD

**Issue by kklepper** [erlang/docker-erlang-example#11]
Hello, 

Thank you for your great work. Working for some time with Yaws, I was curious about Cowboy. I managed to build a container based on your Dockerfile and create certs. 

```
docker@boot2docker:/c/kklepper/test/cowboy$ docker run --rm -v /tmp:/tmp -v /www:/www -p 8012:8080 --name cb  kklepper/cowboy:alpine
No cookie is set or found. This limits the scripts functionality, installing, upgrading, rpc and getting a list of versions will not work.
Exec: /dockerwatch/erts-10.6.4/bin/erlexec -noshell -noinput +Bd -boot /dockerwatch/releases/1.0.0/dockerwatch -mode embedded -boot_var ERTS_LIB_DIR /dockerwatch/lib -config /dockerwatch/releases/1.0.0/sys.config -args_file /dockerwatch/releases/1.0.0/vm.args -- foreground
Root: /dockerwatch
/dockerwatch

```
I do not know what dockerwatch is or does, but the following worked for me:

```
docker@boot2docker:/mnt/sde1/tmp$ curl localhost:8012
<html>
    <head>
    <meta charset="utf-8">
    <title>dockerwatch</title>
    </head><ul>
</ul>
</body>
```
This looked promising.

I hoped to be able to point the root to www, but I didn't know how. I tried to find the file which was invoked with that empty and incomplete unordered list, but `grep -ril "<title>dockerwatch</title>"` just kept working with no output for hours. 

Next I tried to redefine Dockerfile:

```
# test
WORKDIR www
#CMD ["/dockerwatch/bin/dockerwatch", "foreground"]
tail -f /tmp/cookie.txt
```
but this trick didn't work either. Where does Cowboy come into play? 

To make a long story short: I have no idea what I'm doing here. Could you please help me? 

I just want to use Cowboy like Caddy or Apache or NGINX or Yaws. How am I going to do that? 

I don't know anything about Elixir and I sure don't want to use a monster container like the one from 99s (ontouchstart/cowboy 1.47GB, https://github.com/ninenines/cowboy). 

After many hours of research for something which should be very easy to find (docker alpine cowboy) I run out of ideas.

Thank you very much.

**Comment by garazdawi** [comment]
Hello,

I'm not an expert on cowboy by any means and this example is mainly meant to help people that know Erlang but not Docker to get started.

However, I would look at this documentation is cowboy https://ninenines.eu/docs/en/cowboy/2.7/guide/static_files/ to get started. The author of cowboy is also very active on the Erlang irc channel so you may want to ask around there for help.

**Comment by kklepper** [comment]
Thank you very much. I'll do as proposed.
