### ISSUE TITLE
Container will not start

### ISSUE THREAD

**Issue by stevereaver** [erlang/docker-erlang-example#14]
sys log shows the following;

`Jun  4 09:35:05 sulaco 3006f477dede[2167]: Error loading shared library libstdc++.so.6: No such file or directory (needed by /dockerwatch/erts-12.0.2/bin/beam.smp)
Jun  4 09:35:05 sulaco 3006f477dede[2167]: Error loading shared library libgcc_s.so.1: No such file or directory (needed by /dockerwatch/erts-12.0.2/bin/beam.smp)
`

Raising PR to fix docker image.

**Comment by stevereaver** [comment]
PR 15 is ready to merge. https://github.com/erlang/docker-erlang-example/pull/15

**Comment by garazdawi** [comment]
Thanks for the report and fix!
