### ISSUE TITLE
Failed to fetch and copy dep

### ISSUE THREAD

**Issue by immnas** [erlang/docker-erlang-example#21]
Hi,
In my rebar.config file 
i have dependency 
  {mongodb, {git, "https://github.com/emqx/mongodb-erlang.git", {tag, "v3.0.23"}}},
but i am getting error "Failed to fetch and copy dep"
  this repository is actually forked from other same name github. 
  {mongodb, { git, "https://github.com/comtihon/mongodb-erlang", {tag, "v3.2.0"}}}

this works in non docker file but not working with docker one.
   I try also {mongodb, "v3.0.23"} still getting same error.

**Comment by garazdawi** [comment]
Hello! This is not the right place to ask this question. I suggest you go to erlangforums.com and ask there.
