### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by pahagon** [erlang/docker-erlang-example#4]
A idéia dessa primeiro escopo é criar um command line que envia uma msg Hello World via Telegram com as seguintes características:
* Deploy com 3 instancias da aplicação em Regiões diferentes.
* Criar um script de CHAOS monkey para testar
* Ser possível fazer hot reload.

**Comment by garazdawi** [comment]
I'm sorry, but we do not read (what I assume is) Portuguese. Please re-submit in English.
