### ISSUE TITLE
minikube-distributed example is too limited

### ISSUE THREAD

**Issue by cypherfox** [erlang/docker-erlang-example#6]
I am currently trying to get an erlang based application running that requires a minimum of about 20 pods.
(sorry I cannot show the code ATM)

The problem is the list of ports that you need to open, configure individually and apply as lmits to each of the kernes. It makes for exeedingly long service and deployment k8s resource statements. 

I think the example should at least show how to use this with a HA/load-balancing setup 3 or more backend pods.

**Comment by garazdawi** [comment]
The example uses 10 replicated backend nodes by just changing the `replicas` in https://github.com/erlang/docker-erlang-example/blob/minikube-dist/backend-deploy.yaml. I didn't do HA/load-balancing as I could not get it to consistently work with minikube.

**Comment by cypherfox** [comment]
Unless I have been using my Erlang-K8s setup in a wrong way, I understood that you need to have one separate port for each combination of two nodes. Thus one frontend and 10 backend nodes would require 11 ports to be configured on each.

**Comment by garazdawi** [comment]
Only one port has to be configured per node. In the example I use port 12345, try it and see what is done in there.
