### ISSUE TITLE
container fails to start

### ISSUE THREAD

**Issue by mk270** [erlang/docker-erlang-example#9]
I get errors like these in syslog, possibly related to the issue reported at https://github.com/erlang/docker-erlang-otp/issues/235

```
Jun 26 00:39:20 savile d98dae739d24[32358]: No cookie is set or found. This limits the scripts functionality, installing, upgrading, rpc and ge
tting a list of versions will not work.
Jun 26 00:39:20 savile d98dae739d24[32358]: dlsym: Resource temporarily unavailable
Jun 26 00:39:20 savile d98dae739d24[32358]: Aborted (core dumped)
```

**Comment by garazdawi** [comment]
yes, that is the same problem. Not really something we can do about that here until the images are rebuilt.

**Comment by PiotrJustyna** [comment]
For those impatient to wait for the images to get rebuilt or to google, you can use one of the older versions of `alpine` to run the application, e.g. `3.9.4`. In the `Dockerfile`:

```Dockerfile
# Build stage 1
FROM alpine:3.9.4
```
